version: '3.8'

services:
  gender_app:
    build: .
    container_name: gender_app_container
    volumes:
      - ./images:/app/images
    working_dir: /app
    stdin_open: true      # same as -i
    tty: true             # same as -t
